# Instalowanie zależności
install:
    @echo "Brak zależności do zainstalowania dla tej aplikacji w Pythonie."

# Uruchamianie testów jednostkowych
test:
    python3 -m unittest discover -s . -p "test_*.py"

# Uruchamianie aplikacji
run:
    python3 app.py
